export default  [
    // Các đơn hàng hiện tại...
    {
        id: '5',
        recipientName: 'Đức Tuấn',
        address: 'Ký túc xá Bách Khoa, 497 Hoà Hảo, Phường 7, Quận 10, Thành phố Hồ Chí Minh',
        totalAmount: 500000,
        tags: ['Giao sáng',  'Gọi trước'],
        paymentCompleted: true,
        phoneNumber: '0123456789',
        isPickUp: true,
        priority: true,
        status: 'new',
        note: 'Gọi trước',
        timeRecieve: '2024-05-19T12:59:00Z',
    },
    {
        id: '453',
        recipientName: 'Huy Thanh',
        address: '268 Lý Thường Kiệt, phường 7, quận 10, TP.Hồ Chí Minh',
        totalAmount: 500000,
        tags: [ 'Cả ngày', 'Giao chiều', 'Giá trị cao'],
        paymentCompleted: true,
        isPickUp: true,
        priority: false,
        status: 'new',
        timeRecieve: '2024-5-19T12:59:00Z',
    },
    {
        id: '123',
        recipientName: 'Anh Huân',
        address: '142 Cách Mạng Tháng 8, phường 7, quận 10, TP.Hồ Chí Minh',
        totalAmount: 500000,
        tags: ['Giờ hành chính', 'Hàng dễ vỡ', 'Giá trị cao'],
        paymentCompleted: true,
        isPickUp: true,
        priority: false,
        status: 'new',
        timeRecieve: '2024-05-18T13:59:00Z',
    },
    {
        id: '6',
        recipientName: 'Trọng Nghĩa',
        address: '182 Lý Chính Tháng, Phường 9, Quận 3, Thành phố Hồ Chí Minh',
        totalAmount: 600000,
        tags: ['Gọi trước', 'Giao ngời giờ'],
        paymentCompleted: true,
        isPickUp: true,
        priority: true,
        status: 'late',
        timeRecieve: '2024-05-18T13:59:00Z',
    },
    {
        id: '7',
        recipientName: 'Nhật Khang',
        address: 'Đại Học Y Dược, 12 Hồng Bàng, Phường 9, Quận 5, Thành phố Hồ Chí Minh',
        totalAmount: 62000,
        tags: ['Gọi trước', 'Giờ hành chính'],
        paymentCompleted: true,
        isPickUp: true,
        priority: true,
        status: 'late',
        timeRecieve: '2024-05-18T13:59:00Z',
    },
];
