export default  [
    // Các đơn hàng hiện tại...
    {
        id: '5',
        recipientName: 'Đức Tuấn',
        address: 'Ký túc xá Bách Khoa, 497 Hoà Hảo, Phường 7, Quận 10, Thành phố Hồ Chí Minh',
        totalAmount: 500000,
        tags: ['Giao sáng',  'Gọi trước'],
        paymentCompleted: true,
        phoneNumber: '0123456789',
        isPickUp: true,
        priority: true,
        status: 'new',
        note: 'Gọi trước',
        timeRecieve: '2024-05-20T01:59:00Z',
    },
    {
        id: '453',
        recipientName: 'Huy Thanh',
        address: '268 Lý Thường Kiệt, phường 7, quận 10, TP.Hồ Chí Minh',
        totalAmount: 500000,
        tags: [ 'Cả ngày', 'Giao chiều', 'Giá trị cao'],
        paymentCompleted: true,
        isPickUp: true,
        priority: false,
        status: 'new',
        timeRecieve: '2024-5-19T12:59:00Z',
    },
    {
        id: '123',
        recipientName: 'Anh Huân',
        address: '142 Cách Mạng Tháng 8, phường 7, quận 10, TP.Hồ Chí Minh',
        totalAmount: 500000,
        tags: ['Giờ hành chính', 'Hàng dễ vỡ', 'Giá trị cao'],
        paymentCompleted: true,
        isPickUp: true,
        priority: false,
        status: 'new',
        timeRecieve: '2024-05-19T13:59:00Z',
    },
    {
        id: '6',
        recipientName: 'Trọng Nghĩa',
        address: '182 Lý Chính Tháng, Phường 9, Quận 3, Thành phố Hồ Chí Minh',
        totalAmount: 600000,
        tags: ['Gọi trước', 'Giao ngời giờ'],
        paymentCompleted: true,
        isPickUp: true,
        priority: true,
        status: 'late',
        timeRecieve: '2024-05-19T13:59:00Z',
    },
    {
        id: '7',
        recipientName: 'Người nhận 7',
        address: 'Địa chỉ 7',
        totalAmount: 700000,
        tags: ['tag13', 'tag14'],
        paymentCompleted: true,
        isPickUp: true,
        priority: true,
        status: 'delete',
        timeRecieve: '2022-03-14T01:59:00Z',
    },
    {
        id: '8',
        recipientName: 'Người nhận 8',
        address: 'Địa chỉ 8',
        totalAmount: 800000,
        tags: ['tag15', 'tag16'],
        paymentCompleted: true,
        isPickUp: true,
        priority: true,
        status: 'change',
        timeRecieve: '2022-03-14T01:59:00Z',
    },
    {
        id: '9',
        recipientName: 'Người nhận 9',
        address: 'Địa chỉ 9',
        totalAmount: 900000,
        tags: ['tag17', 'tag18'],
        paymentCompleted: true,
        isPickUp: true,
        priority: true,
        status: 'normal',
        timeRecieve: '2022-03-14T01:59:00Z',
    },
    {
        id: '10',
        recipientName: 'Người nhận 10',
        address: 'Địa chỉ 10',
        totalAmount: 1000000,
        tags: ['tag19', 'tag20'],
        paymentCompleted: true,
        isPickUp: true,
        priority: true,
        status: 'normal',
        timeRecieve: '2022-03-14T01:59:00Z',
    },
];
